language: node_js
node_js: "6"
cache:
  directories:
    - "node_modules"
before_deploy: "webpack"
env: CALLBACK="https://thebookingmanager.herokuapp.com"
deploy:
  provider: heroku
  app: thebookingmanager
  skip_cleanup: true
  api_key:
    secure: 04af2270-3e6e-4131-ab9d-446486696bdd
  on: staging